// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lallison/h_skills_project/internal/service/usecase/status (interfaces: StatusRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	slog "log/slog"
	reflect "reflect"

	entities "github.com/lallison/h_skills_project/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusRepository is a mock of StatusRepository interface.
type MockStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatusRepositoryMockRecorder
}

// MockStatusRepositoryMockRecorder is the mock recorder for MockStatusRepository.
type MockStatusRepositoryMockRecorder struct {
	mock *MockStatusRepository
}

// NewMockStatusRepository creates a new mock instance.
func NewMockStatusRepository(ctrl *gomock.Controller) *MockStatusRepository {
	mock := &MockStatusRepository{ctrl: ctrl}
	mock.recorder = &MockStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusRepository) EXPECT() *MockStatusRepositoryMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockStatusRepository) Status(arg0 *slog.Logger) (*entities.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(*entities.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockStatusRepositoryMockRecorder) Status(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStatusRepository)(nil).Status), arg0)
}
