// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lallison/h_skills_project/internal/service/gateways/computer (interfaces: ComputerUseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	slog "log/slog"
	reflect "reflect"

	entities "github.com/lallison/h_skills_project/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockComputerUseCase is a mock of ComputerUseCase interface.
type MockComputerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockComputerUseCaseMockRecorder
}

// MockComputerUseCaseMockRecorder is the mock recorder for MockComputerUseCase.
type MockComputerUseCaseMockRecorder struct {
	mock *MockComputerUseCase
}

// NewMockComputerUseCase creates a new mock instance.
func NewMockComputerUseCase(ctrl *gomock.Controller) *MockComputerUseCase {
	mock := &MockComputerUseCase{ctrl: ctrl}
	mock.recorder = &MockComputerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputerUseCase) EXPECT() *MockComputerUseCaseMockRecorder {
	return m.recorder
}

// ComputerByID mocks base method.
func (m *MockComputerUseCase) ComputerByID(arg0 *slog.Logger, arg1 string) (*entities.Computer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputerByID", arg0, arg1)
	ret0, _ := ret[0].(*entities.Computer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputerByID indicates an expected call of ComputerByID.
func (mr *MockComputerUseCaseMockRecorder) ComputerByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputerByID", reflect.TypeOf((*MockComputerUseCase)(nil).ComputerByID), arg0, arg1)
}

// Computers mocks base method.
func (m *MockComputerUseCase) Computers(arg0 *slog.Logger) ([]*entities.Computer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Computers", arg0)
	ret0, _ := ret[0].([]*entities.Computer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Computers indicates an expected call of Computers.
func (mr *MockComputerUseCaseMockRecorder) Computers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Computers", reflect.TypeOf((*MockComputerUseCase)(nil).Computers), arg0)
}

// CreateComputer mocks base method.
func (m *MockComputerUseCase) CreateComputer(arg0 *slog.Logger, arg1 *entities.Computer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComputer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateComputer indicates an expected call of CreateComputer.
func (mr *MockComputerUseCaseMockRecorder) CreateComputer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComputer", reflect.TypeOf((*MockComputerUseCase)(nil).CreateComputer), arg0, arg1)
}
