// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lallison/h_skills_project/internal/application (interfaces: ComputerGateways)

// Package mocks is a generated GoMock package.
package mocks

import (
	slog "log/slog"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockComputerGateways is a mock of ComputerGateways interface.
type MockComputerGateways struct {
	ctrl     *gomock.Controller
	recorder *MockComputerGatewaysMockRecorder
}

// MockComputerGatewaysMockRecorder is the mock recorder for MockComputerGateways.
type MockComputerGatewaysMockRecorder struct {
	mock *MockComputerGateways
}

// NewMockComputerGateways creates a new mock instance.
func NewMockComputerGateways(ctrl *gomock.Controller) *MockComputerGateways {
	mock := &MockComputerGateways{ctrl: ctrl}
	mock.recorder = &MockComputerGatewaysMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputerGateways) EXPECT() *MockComputerGatewaysMockRecorder {
	return m.recorder
}

// ComputerByID mocks base method.
func (m *MockComputerGateways) ComputerByID(arg0 *slog.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputerByID", arg0)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// ComputerByID indicates an expected call of ComputerByID.
func (mr *MockComputerGatewaysMockRecorder) ComputerByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputerByID", reflect.TypeOf((*MockComputerGateways)(nil).ComputerByID), arg0)
}

// Computers mocks base method.
func (m *MockComputerGateways) Computers(arg0 *slog.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Computers", arg0)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Computers indicates an expected call of Computers.
func (mr *MockComputerGatewaysMockRecorder) Computers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Computers", reflect.TypeOf((*MockComputerGateways)(nil).Computers), arg0)
}

// CreateComputer mocks base method.
func (m *MockComputerGateways) CreateComputer(arg0 *slog.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComputer", arg0)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// CreateComputer indicates an expected call of CreateComputer.
func (mr *MockComputerGatewaysMockRecorder) CreateComputer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComputer", reflect.TypeOf((*MockComputerGateways)(nil).CreateComputer), arg0)
}
