FROM golang:alpine AS builder

WORKDIR /usr/local/src

RUN apk --no-cache add bash make
#RUN go install -mod=mod github.com/githubnemo/CompileDaemon

COPY ["./go.mod", "./go.sum", "./"]
RUN go mod download

COPY ./ ./
#RUN CompileDaemon --build="go build -o bin/api ./cmd/api"
RUN make build-api

FROM alpine AS runner

COPY --from=builder /usr/local/src/bin/api ./

CMD ["./api"]