FROM golang:alpine

WORKDIR /usr/local/src

COPY . .

RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT ComplieDaemon --build="go build -o main ./cmd/h_skills_project" --command=./main