FROM golang:alpine

WORKDIR /usr/local/src

COPY . .

RUN go mod download
RUN go install -mod=mod github.com/githubnemo/CompileDaemon

EXPOSE 8080

ENTRYPOINT CompileDaemon --build="go build -o main ./cmd/h_skills_project" --command="./main"