services:
  development-api:
    image: api:development
    container_name: development-api
    env_file:
      - .env.development
    hostname: development-api
    ports:
      - "8080:8080"
    networks:
      - development

networks:
  development:
    driver: bridge
