services:
  development-api:
    image: api:development
    container_name: development-api
    env_file:
      - .env.development
    hostname: development-api
    ports:
      - "8080:8080"
    depends_on:
      development-db:
        condition: service_healthy
    networks:
      - development

  development-db:
    image: postgres:latest
    container_name: development-database
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./.database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - development

networks:
  development:
    driver: bridge
